/* Generated by AN DISI Unibo */ 
package it.unibo.waiter

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waiter ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var tabFree = ""  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("waiter is starting..I'm HOME!")
						delay(200) 
						discardMessages = false
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("reqHandler") { //this:State
					action { //it:State
						println("I'm HOME, waiting for a request!")
					}
					 transition(edgeName="t00",targetState="acceptance",cond=whenRequest("checkAvail"))
					transition(edgeName="t01",targetState="takingOrder",cond=whenDispatch("readyToOrder"))
					transition(edgeName="t02",targetState="collectingDrink",cond=whenDispatch("ready"))
					transition(edgeName="t03",targetState="exitClient",cond=whenDispatch("exitReq"))
					transition(edgeName="t04",targetState="payment",cond=whenDispatch("endTime"))
				}	 
				state("acceptance") { //this:State
					action { //it:State
						request("tabStatus", "tabStatus(1)" ,"table1" )  
						if( checkMsgContent( Term.createTerm("tabState(X)"), Term.createTerm("tabState(STATUS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 tabFree = payloadArg(0)  
								if(  tabFree != "free and clean" 
								 ){request("tabStatus", "tabStatus(1)" ,"table2" )  
								if( checkMsgContent( Term.createTerm("tabState(X)"), Term.createTerm("tabState(STATUS)"), 
								                        currentMsg.msgContent()) ) { //set msgArgList
										 tabFree = payloadArg(0)  
										if(  tabFree != "free and clean" 
										 ){answer("checkAvail", "waitingTime", "waitingTime(2000)"   )  
										}
										else
										 {answer("checkAvail", "waitingTime", "waitingTime(0)"   )  
										 }
								}
								}
								else
								 {answer("checkAvail", "waitingTime", "waitingTime(0)"   )  
								 }
						}
						 tabFree = ""  
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("collectingDrink") { //this:State
					action { //it:State
						println("I'm collecting the drink from the barman")
						delay(200) 
						println("I'm taking the drink to the client")
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("takingOrder") { //this:State
					action { //it:State
						println("I'm collecting the order from the client")
						request("take", "take(1)" ,"client" )  
						if( checkMsgContent( Term.createTerm("order(X)"), Term.createTerm("order(ORDER)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("orderReq", "orderReq(${payloadArg(0)})" ,"barman" ) 
						}
						println("I'm taking the drink to the client")
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("exitClient") { //this:State
					action { //it:State
						println("Client requested to exit! Proceeding to the payment")
					}
					 transition( edgeName="goto",targetState="payment", cond=doswitch() )
				}	 
				state("payment") { //this:State
					action { //it:State
						println("Collecting the money!")
						request("collect", "collect(1)" ,"client" )  
						if( checkMsgContent( Term.createTerm("payment(X)"), Term.createTerm("payment(MONEY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 println(payloadArg(0) + "� collected! Have a nice day!")  
						}
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
			}
		}
}
