/* Generated by AN DISI Unibo */ 
package it.unibo.barman

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Barman ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var ID = "" 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
					}
					 transition( edgeName="goto",targetState="waitingForOrder", cond=doswitch() )
				}	 
				state("waitingForOrder") { //this:State
					action { //it:State
						println("[BARMAN] Waiting for events...")
					}
					 transition(edgeName="t031",targetState="makeTea",cond=whenEvent("newOrderEvent"))
					transition(edgeName="t032",targetState="teaReady",cond=whenEvent("prepare"))
				}	 
				state("makeTea") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("newOrderEvent(X)"), Term.createTerm("newOrderEvent(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								ID = payloadArg(0) 
								println("[BARMAN] Making some delicious tea...")
						}
					}
					 transition( edgeName="goto",targetState="waitingForOrder", cond=doswitch() )
				}	 
				state("teaReady") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("prepare(ID)"), Term.createTerm("prepare(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ID = payloadArg(0)  
								println("[BARMAN] The order for client $ID is ready!")
								forward("ready", "ready($ID)" ,"resourcemodel" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitingForOrder", cond=doswitch() )
				}	 
			}
		}
}
