/* Generated by AN DISI Unibo */ 
package it.unibo.clientsimulator

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Clientsimulator ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				var tempResult = "no"	
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("[CLIENT] Client STARTED")
						discardMessages = false
						delay(10000) 
					}
					 transition(edgeName="t029",targetState="askToEnter",cond=whenEvent("nextState"))
				}	 
				state("askToEnter") { //this:State
					action { //it:State
						println("[CLIENT] Knock Knock, I'm here")
						request("notify", "notify" ,"smartbell" )  
					}
					 transition(edgeName="t030",targetState="handleReply",cond=whenReply("tempResult"))
				}	 
				state("handleReply") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("tempResult(X)"), Term.createTerm("tempResult(RES)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 tempResult = payloadArg(0)  
						}
					}
					 transition( edgeName="goto",targetState="waitToEnter", cond=doswitchGuarded({ tempResult == "yes"  
					}) )
					transition( edgeName="goto",targetState="exit", cond=doswitchGuarded({! ( tempResult == "yes"  
					) }) )
				}	 
				state("waitToEnter") { //this:State
					action { //it:State
					}
					 transition(edgeName="t131",targetState="wait",cond=whenDispatch("inform"))
					transition(edgeName="t132",targetState="enter",cond=whenDispatch("accept"))
				}	 
				state("wait") { //this:State
					action { //it:State
						println("[CLIENT] I have to wait")
						if( checkMsgContent( Term.createTerm("inform(X)"), Term.createTerm("inform(TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Time = payloadArg(0).toLong() 
								delay(Time)
						}
					}
					 transition( edgeName="goto",targetState="enter", cond=doswitch() )
				}	 
				state("enter") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("accept(ID)"), Term.createTerm("accept(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								delay(20000) 
								println("[CLIENT] Choosing a drink")
						}
					}
					 transition(edgeName="t033",targetState="askForWaiter",cond=whenEvent("nextState"))
				}	 
				state("askForWaiter") { //this:State
					action { //it:State
						forward("readyToOrder", "readyToOrder(1)" ,"waiter" ) 
					}
					 transition(edgeName="t034",targetState="makeOrder",cond=whenRequest("take"))
				}	 
				state("makeOrder") { //this:State
					action { //it:State
						println("[CLIENT] A Na-tea-li please")
						answer("take", "order", "order(tea)"   )  
					}
					 transition(edgeName="t035",targetState="drink",cond=whenDispatch("serveDrink"))
				}	 
				state("drink") { //this:State
					action { //it:State
						println("[CLIENT] *sip sip* Delicious tea")
					}
					 transition(edgeName="t036",targetState="askToPay",cond=whenEvent("nextState"))
				}	 
				state("askToPay") { //this:State
					action { //it:State
						println("[CLIENT] I want to pay")
						forward("exitReq", "exitReq(1)" ,"waiter" ) 
					}
					 transition(edgeName="t037",targetState="pay",cond=whenRequest("collect"))
				}	 
				state("pay") { //this:State
					action { //it:State
						println("[CLIENT] Paying")
						answer("collect", "payment", "payment(10)"   )  
					}
					 transition(edgeName="t038",targetState="exit",cond=whenEvent("nextState"))
				}	 
				state("exit") { //this:State
					action { //it:State
						println("[CLIENT] Client EXIT Byeeee!")
						terminate(1)
					}
				}	 
			}
		}
}
