/* Generated by AN DISI Unibo */ 
package it.unibo.smartbell

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Smartbell ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		  
				var T     = 37.0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
					}
					 transition( edgeName="goto",targetState="waitingForClient", cond=doswitch() )
				}	 
				state("waitingForClient") { //this:State
					action { //it:State
						println("[SMARTBELL] Waiting for a new client...")
					}
					 transition(edgeName="t040",targetState="checkTemp",cond=whenRequest("notify"))
				}	 
				state("checkTemp") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("notify(X)"), Term.createTerm("notify(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 T = payloadArg(0).toDouble()  
								println("[SMARTBELL] Checking your temperature...")
								if(  T > 37.5  
								 ){println("[SMARTBELL] You should go to the hospital! ")
								answer("notify", "tempResult", "tempResult(no)"   )  
								}
								else
								 {println("[SMARTBELL] Your temperature is ok ")
								 answer("notify", "tempResult", "tempResult(yes)"   )  
								 }
						}
					}
					 transition( edgeName="goto",targetState="waitingForClient", cond=doswitchGuarded({ T > 37.5  
					}) )
					transition( edgeName="goto",targetState="waiterInfo", cond=doswitchGuarded({! ( T > 37.5  
					) }) )
				}	 
				state("waiterInfo") { //this:State
					action { //it:State
						println("[SMARTBELL] Checking table situation... ")
						forward("newClient", "newClient(0)" ,"resourcemodel" ) 
					}
					 transition(edgeName="t141",targetState="informClient",cond=whenEvent("waitingTimeEvent"))
				}	 
				state("informClient") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("waitingTimeEvent(ID,X)"), Term.createTerm("waitingTimeEvent(ID,X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(1).toDouble() == 0.0 	 
								 ){println("[SMARTBELL] A waiter is coming... ")
								forward("accept", "accept(${payloadArg(0)})" ,"clientsmanager" ) 
								}
								else
								 {println("[SMARTBELL] You have to wait... ")
								 forward("inform", "inform(${payloadArg(0)},${payloadArg(1)})" ,"clientsmanager" ) 
								 }
						}
					}
					 transition( edgeName="goto",targetState="waitingForClient", cond=doswitch() )
				}	 
			}
		}
}
