/* Generated by AN DISI Unibo */ 
package it.unibo.waiter

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waiter ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				var WhatImDoing = "athome" 
				var TeatableNumber = ""
				var Teatable = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[WAITER] waiter is starting..I'm HOME!")
						discardMessages = false
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("reqHandler") { //this:State
					action { //it:State
						println("[WAITER] Waiting for a request!")
					}
					 transition(edgeName="t011",targetState="handleChange",cond=whenEvent("waiterTaskChangedEvent"))
					transition(edgeName="t012",targetState="movementHelper",cond=whenDispatch("moveTo"))
				}	 
				state("handleChange") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("waiterTaskChangedEvent(X,T)"), Term.createTerm("waiterTaskChangedEvent(T,X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								 				WhatImDoing = payloadArg(0)
								 				if(payloadArg(1) == "1" || payloadArg(1) == "2") {
								 					TeatableNumber = payloadArg(1)
								 					Teatable = "teatable" + TeatableNumber
								 				}
								println("[WAITER] New task: $WhatImDoing")
								
											when(WhatImDoing) {
												"reachEntranceDoor" -> { 
								forward("moveTo", "moveTo(entrancedoor)" ,"waiter" ) 
								}
												"convoyTable" -> { 
								forward("moveTo", "moveTo($Teatable)" ,"waiter" ) 
								}
												"takingOrder" -> { 
								forward("moveTo", "moveTo($Teatable)" ,"waiter" ) 
								}
												"collectingDrink" -> { 
								forward("moveTo", "moveTo(barman)" ,"waiter" ) 
								}
												"bringingDrinkToClient" -> { 
								forward("moveTo", "moveTo($Teatable)" ,"waiter" ) 
								}
												"collectingPayment" -> { 
								forward("moveTo", "moveTo($Teatable)" ,"waiter" ) 
								}
												"convoyExit" -> { 
								forward("moveTo", "moveTo(exitdoor)" ,"waiter" ) 
								}
												"returnHome" -> { 
								forward("moveTo", "moveTo(home)" ,"waiter" ) 
								}	
												"sanitizing" -> { 
								forward("moveTo", "moveTo($Teatable)" ,"waiter" ) 
								}
									
												"stepAhead" -> { 
								forward("doMove", "doMove(w)" ,"planner" ) 
								}
												"turnLeft" -> { 
								forward("doMove", "doMove(l)" ,"planner" ) 
								}
												"turnRight" -> { 
								forward("doMove", "doMove(r)" ,"planner" ) 
								}
													
												"forceExit" -> { 
								forward("moveTo", "moveTo($Teatable)" ,"waiter" ) 
								}
								 			} 
						}
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("clientReady") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("takingOrder") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("order(ID,X)"), Term.createTerm("order(ID,O)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var ID = payloadArg(0) 
												var O = payloadArg(1)
								forward("orderReq", "orderReq($ID,$O)" ,"resourcemodel" ) 
								println("[WAITER] I'm transmitting the order to the barman")
								forward("taskDone", "taskDone($WhatImDoing,0)" ,"resourcemodel" ) 
						}
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("servingDrinkToClient") { //this:State
					action { //it:State
						println("[WAITER] Serving the drink")
						forward("taskDone", "taskDone($WhatImDoing,0)" ,"resourcemodel" ) 
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("payment") { //this:State
					action { //it:State
						println("[WAITER] Collecting the money!")
					}
					 transition(edgeName="t013",targetState="handlePayment",cond=whenDispatch("payment"))
				}	 
				state("handlePayment") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("payment(ID,X)"), Term.createTerm("payment(ID,MONEY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 println("[WAITER] " + payloadArg(0) + " EUR collected! Have a nice day!")  
								forward("taskDone", "taskDone($WhatImDoing,${payloadArg(0)})" ,"resourcemodel" ) 
						}
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("cleaningTable") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("cleanTable(T)"), Term.createTerm("cleanTable(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								TeatableNumber = payloadArg(0) 
								println("[WAITER] Cleaning $Teatable!")
								delay(5000) 
								forward("taskDone", "taskDone($WhatImDoing,$TeatableNumber)" ,"resourcemodel" ) 
						}
					}
					 transition( edgeName="goto",targetState="reqHandler", cond=doswitch() )
				}	 
				state("movementHelper") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveTo(X)"), Term.createTerm("moveTo(L)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								val Location = payloadArg(0) 
								request("askWhere", "askWhere($Location)" ,"resourcemodel" )  
						}
						if( checkMsgContent( Term.createTerm("location(X,Y)"), Term.createTerm("location(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val XT = payloadArg(0)
											   	val YT = payloadArg(1)			  
								request("movetoCell", "movetoCell($XT,$YT)" ,"planner" )  
						}
					}
					 transition(edgeName="t114",targetState="movementHelper",cond=whenReply("location"))
					transition(edgeName="t115",targetState="handleAtCell",cond=whenReply("atcell"))
				}	 
				state("handleAtCell") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("atcell(X,Y)"), Term.createTerm("atcell(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 when(WhatImDoing) {
												"takingOrder" ->  {
								 } 
												"bringingDrinkToClient" ->  {
								 } 
												"collectingPayment" ->  {
								 } 
												"sanitizing" ->  {
								forward("cleanTable", "cleanTable($TeatableNumber)" ,"waiter" ) 
								}
												"forceExit" -> { 
								forward("listenRequests", "listenRequests(1)" ,"waiter" ) 
								forward("taskDone", "taskDone($WhatImDoing,$TeatableNumber)" ,"resourcemodel" ) 
								}
												else -> {
								forward("listenRequests", "listenRequests(1)" ,"waiter" ) 
								forward("taskDone", "taskDone($WhatImDoing,0)" ,"resourcemodel" ) 
								}
											} 
						}
					}
					 transition(edgeName="t116",targetState="movementHelper",cond=whenDispatch("moveTo"))
					transition(edgeName="t117",targetState="takingOrder",cond=whenDispatch("order"))
					transition(edgeName="t118",targetState="servingDrinkToClient",cond=whenDispatch("takeDrink"))
					transition(edgeName="t119",targetState="handlePayment",cond=whenDispatch("payment"))
					transition(edgeName="t120",targetState="cleaningTable",cond=whenDispatch("cleanTable"))
					transition(edgeName="t121",targetState="reqHandler",cond=whenDispatch("listenRequests"))
				}	 
			}
		}
}
